Ivoz\Provider\Domain\Model\Brand\Brand:
  attributes:
    access_control: 'user.isSuperAdmin()'
Ivoz\Provider\Domain\Model\Brand\Invoice:
Ivoz\Provider\Domain\Model\Brand\Logo:
#Ivoz\Provider\Domain\Model\Administrator\Administrator:
#Ivoz\Provider\Domain\Model\ApplicationServer\ApplicationServer:
#Ivoz\Provider\Domain\Model\BrandService\BrandService:
Ivoz\Provider\Domain\Model\BrandUrl\BrandUrl:
  attributes:
    access_control: 'user.isSuperAdmin()'
#Ivoz\Provider\Domain\Model\Calendar\Calendar:
#Ivoz\Provider\Domain\Model\CallAcl\CallAcl:
#Ivoz\Provider\Domain\Model\CallAclRelMatchList\CallAclRelMatchList:
#Ivoz\Provider\Domain\Model\CallForwardSetting\CallForwardSetting:
Ivoz\Provider\Domain\Model\Company\Company:
  attributes:
    access_control: 'user.isSuperAdmin()'
#Ivoz\Provider\Domain\Model\CompanyService\CompanyService:
#Ivoz\Provider\Domain\Model\ConditionalRoute\ConditionalRoute:
#Ivoz\Provider\Domain\Model\ConditionalRoutesCondition\ConditionalRoutesCondition:
#Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelMatchlist\ConditionalRoutesConditionsRelMatchlist:
#Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelSchedule\ConditionalRoutesConditionsRelSchedule:
#Ivoz\Provider\Domain\Model\ConditionalRoutesConditionsRelCalendar\ConditionalRoutesConditionsRelCalendar:
#Ivoz\Provider\Domain\Model\ConferenceRoom\ConferenceRoom:
#Ivoz\Provider\Domain\Model\Country\Country:
#Ivoz\Provider\Domain\Model\Ddi\Ddi:
#Ivoz\Provider\Domain\Model\Domain\Domain:
#Ivoz\Provider\Domain\Model\Extension\Extension:
#Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter:
#Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackList:
#Ivoz\Provider\Domain\Model\ExternalCallFilterRelCalendar\ExternalCallFilterRelCalendar:
#Ivoz\Provider\Domain\Model\ExternalCallFilterRelSchedule\ExternalCallFilterRelSchedule:
#Ivoz\Provider\Domain\Model\ExternalCallFilterWhiteList\ExternalCallFilterWhiteList:
#Ivoz\Provider\Domain\Model\FaxesInOut\FaxesInOut:
#Ivoz\Provider\Domain\Model\Fax\Fax:
#Ivoz\Provider\Domain\Model\Feature\Feature:
#Ivoz\Provider\Domain\Model\FeaturesRelBrand\FeaturesRelBrand:
#Ivoz\Provider\Domain\Model\FeaturesRelCompany\FeaturesRelCompany:
#Ivoz\Provider\Domain\Model\FixedCost\FixedCost:
#Ivoz\Provider\Domain\Model\FixedCostsRelInvoice\FixedCostsRelInvoice:
#Ivoz\Provider\Domain\Model\Friend\Friend:
#Ivoz\Provider\Domain\Model\FriendsPattern\FriendsPattern:
#Ivoz\Provider\Domain\Model\HolidayDate\HolidayDate:
#Ivoz\Provider\Domain\Model\HuntGroup\HuntGroup:
#Ivoz\Provider\Domain\Model\HuntGroupsRelUser\HuntGroupsRelUser:
#Ivoz\Provider\Domain\Model\Invoice\Invoice:
#Ivoz\Provider\Domain\Model\InvoiceTemplate\InvoiceTemplate:
#Ivoz\Provider\Domain\Model\IvrEntry\IvrEntry:
#Ivoz\Provider\Domain\Model\Ivr\Ivr:
#Ivoz\Provider\Domain\Model\IvrExcludedExtension\IvrExcludedExtension:
Ivoz\Provider\Domain\Model\Language\Language:
  attributes:
    access_control: 'user.isSuperAdmin()'
Ivoz\Provider\Domain\Model\Language\Name:
#Ivoz\Provider\Domain\Model\LcrGateway\LcrGateway:
#Ivoz\Provider\Domain\Model\LcrRule\LcrRule:
#Ivoz\Provider\Domain\Model\LcrRuleTarget\LcrRuleTarget:
#Ivoz\Provider\Domain\Model\Locution\Locution:
#Ivoz\Provider\Domain\Model\MatchList\MatchList:
#Ivoz\Provider\Domain\Model\MatchListPattern\MatchListPattern:
#Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySet:
#Ivoz\Provider\Domain\Model\MusicOnHold\MusicOnHold:
#Ivoz\Provider\Domain\Model\OutgoingDdiRule\OutgoingDdiRule:
#Ivoz\Provider\Domain\Model\OutgoingDdiRulesPattern\OutgoingDdiRulesPattern:
#Ivoz\Provider\Domain\Model\OutgoingRouting\OutgoingRouting:
#Ivoz\Provider\Domain\Model\ParsedCdr\ParsedCdr:
#Ivoz\Provider\Domain\Model\PeeringContract\PeeringContract:
#Ivoz\Provider\Domain\Model\PeerServer\PeerServer:
#Ivoz\Provider\Domain\Model\PickUpGroup\PickUpGroup:
#Ivoz\Provider\Domain\Model\PickUpRelUser\PickUpRelUser:
#Ivoz\Provider\Domain\Model\PricingPlan\PricingPlan:
#Ivoz\Provider\Domain\Model\PricingPlansRelCompany\PricingPlansRelCompany:
#Ivoz\Provider\Domain\Model\PricingPlansRelTargetPattern\PricingPlansRelTargetPattern:
#Ivoz\Provider\Domain\Model\ProxyTrunk\ProxyTrunk:
#Ivoz\Provider\Domain\Model\ProxyUser\ProxyUser:
#Ivoz\Provider\Domain\Model\QueueMember\QueueMember:
#Ivoz\Provider\Domain\Model\Queue\Queue:
#Ivoz\Provider\Domain\Model\Recording\Recording:
#Ivoz\Provider\Domain\Model\RetailAccount\RetailAccount:
#Ivoz\Provider\Domain\Model\RoutingPatternGroup\RoutingPatternGroup:
#Ivoz\Provider\Domain\Model\RoutingPatternGroupsRelPattern\RoutingPatternGroupsRelPattern:
#Ivoz\Provider\Domain\Model\RoutingPattern\RoutingPattern:
#Ivoz\Provider\Domain\Model\Schedule\Schedule:
#Ivoz\Provider\Domain\Model\Service\Service:
#Ivoz\Provider\Domain\Model\TargetPattern\TargetPattern:
#Ivoz\Provider\Domain\Model\TerminalManufacturer\TerminalManufacturer:
#Ivoz\Provider\Domain\Model\TerminalModel\TerminalModel:
#Ivoz\Provider\Domain\Model\Terminal\Terminal:
#Ivoz\Provider\Domain\Model\Timezone\Timezone:
#Ivoz\Provider\Domain\Model\TransformationRuleSet\TransformationRuleSet:
#Ivoz\Provider\Domain\Model\TransformationRule\TransformationRule:
#Ivoz\Provider\Domain\Model\User\User:
#Ivoz\Kam\Domain\Model\PikeTrusted\PikeTrusted: