# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html

imports:
  - { resource: "@CoreBundle/Resources/config/services.yml" }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  fastagi:
    synthetic: true


  ##################################
  ## External Services
  ##################################
  PhpMimeMailParser\Parser: ~

  ##################################
  ## Helpers & Wrappers
  ##################################
  Agi\Wrapper:
    lazy: true
    arguments:
      $fastagi: '@fastagi'
      $locutionPathResolver: '@Service\CommonStoragePathResolver::LocutionEncodedFile'
      $colorizer: '@Agi\Colorizer'

  Agi\Colorizer:
    arguments: ~

  Helpers\EndpointResolver:
    arguments: ~

  Voicemail\Sender:
    arguments:
      $parser: '@PhpMimeMailParser\Parser'
      $mailer: '@mailer'
      $templatesDir: '%kernel.root_dir%/../templates'
      $fromName: '%mailer_default_fromname%'
      $fromAdress: '%mailer_default_fromaddress%'

  ##################################
  ## Handlers
  ##################################
  Dialplan\Headers:
    arguments: ~

  Dialplan\Trunks:
    arguments: ~

  Dialplan\Users:
    arguments: ~

  Dialplan\Retailers:
    arguments: ~

  Dialplan\Friends:
    arguments: ~

  Dialplan\UserStatus:
    arguments: ~

  Dialplan\HuntGroups:
    arguments: ~

  Dialplan\HuntGroupStatus:
    arguments: ~

  Dialplan\Queues:
    arguments: ~

  Dialplan\QueueStatus:
    arguments: ~

  Dialplan\FaxDial:
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $faxStoragePathResolver:
        '@Service\CommonStoragePathResolver::FaxesInOutFile'

  Dialplan\FaxDialStatus:
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Dialplan\FaxSend:
    arguments: ~

  Dialplan\FaxSendStatus:
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Dialplan\FaxReceiveStatus:
    arguments: ~

  ##################################
  ## Actions
  ##################################
  Agi\Action\CallForwardAction:
    lazy: true
    arguments: ~

  Agi\Action\ConditionalRouteAction:
    lazy: true
    arguments: ~

  Agi\Action\ConferenceRoomAction:
    lazy: true
    arguments: ~

  Agi\Action\DdiAction:
    lazy: true
    arguments: ~

  Agi\Action\ExtensionAction:
    lazy: true
    arguments: ~

  Agi\Action\FaxReceiveAction:
    lazy: true
    arguments: ~

  Agi\Action\FaxReceiveStatusAction:
    lazy: true
    arguments:
      $entityPersister: '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'
      $mailer: '@mailer'
      $fromName: '%mailer_default_fromname%'
      $fromAdress: '%mailer_default_fromaddress%'

  Agi\Action\FriendCallAction:
    lazy: true
    arguments: ~

  Agi\Action\HuntGroupAction:
    lazy: true
    arguments: ~

  Agi\Action\HuntGroupCallAction:
    lazy: true
    arguments: ~

  Agi\Action\HuntGroupStatusAction:
    lazy: true
    arguments: ~

  Agi\Action\IvrAction:
    lazy: true
    arguments: ~

  Agi\Action\QueueAction:
    lazy: true
    arguments: ~

  Agi\Action\QueueCallAction:
    lazy: true
    arguments: ~

  Agi\Action\QueueFullAction:
    lazy: true
    arguments: ~

  Agi\Action\QueueTimeoutAction:
    lazy: true
    arguments: ~

  Agi\Action\RetailCallAction:
    lazy: true
    arguments: ~

  Agi\Action\RouterAction:
    lazy: true
    arguments: ~

  Agi\Action\UserCallAction:
    lazy: true
    arguments: ~

  Agi\Action\UserStatusAction:
    lazy: true
    arguments: ~

  Agi\Action\ExternalFilterAction:
    lazy: true
    arguments: ~

  Agi\Action\ExternalDdiCallAction:
    lazy: true
    arguments: ~

  Agi\Action\ExternalFaxCallAction:
    lazy: true
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Agi\Action\ExternalFriendCallAction:
    lazy: true
    arguments: ~

  Agi\Action\ExternalRetailCallAction:
    lazy: true
    arguments: ~

  Agi\Action\ExternalUserCallAction:
    lazy: true
    arguments: ~

  Agi\Action\ServiceAction:
    lazy: true
    arguments:
      $entityPersister:
        '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Agi\Action\VoiceMailAction:
    lazy: true
    arguments: ~
