services:
  _defaults:
    autowire: true
    public: false

  #########################################################
  ## Trunks XMLRPC Requests
  #########################################################
  XmlRpc\XmlRpcTrunksRequest::DialplanReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcTrunksRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'dialplan.reload'

  XmlRpc\XmlRpcTrunksRequest::DispatcherReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcTrunksRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'dispatcher.reload'

  XmlRpc\XmlRpcTrunksRequest::LcrReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcTrunksRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'lcr.reload'

  XmlRpc\XmlRpcTrunksRequest::PermissionsTrustedReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcTrunksRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'permissions.trustedReload'

  XmlRpc\XmlRpcTrunksRequest::UacRegReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcTrunksRequest
    arguments:
      $xmlrpc:
        '@Jobs\XmlrpcDelayed'
      $rpcMethod:
        'uac.reg_reload'

  #########################################################
  ## Users XMLRPC Requests
  #########################################################
  XmlRpc\XmlRpcUsersRequest::DispatcherReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcUsersRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'dispatcher.reload'

  XmlRpc\XmlRpcUsersRequest::DomainReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcUsersRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'domain.reload'

  XmlRpc\XmlRpcUsersRequest::PermissionsTrustedReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcUsersRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'permissions.trustedReload'

  XmlRpc\XmlRpcUsersRequest::DialplanReload:
    class: Ivoz\Core\Infrastructure\Domain\Service\XmlRpc\XmlRpcUsersRequest
    arguments:
      $xmlrpc:
        '@IvozProvider\Gearmand\Jobs\Xmlrpc'
      $rpcMethod:
        'dialplan.reload'
