Ivoz\Provider\Domain\Model\Brand\Invoice:
  attributes:
    nif:
      groups: ['list', 'get']

Ivoz\Provider\Domain\Model\Brand\Brand:
  attributes:
    id:
      groups: ['list', 'get']
    name:
      groups: ['list', 'get']
    invoice:
      groups: ['list', 'get']
