services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ################################################
  ## Override $propertyNameCollectionFactory
  ################################################
  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory: ~

  Ivoz\Api\Swagger\Serializer\DocumentationNormalizerDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    decoration_priority: 10
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Swagger\Serializer\DocumentationNormalizerDecorator.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'

  Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator:
    decorates: 'api_platform.subresource_operation_factory'
    decoration_priority: 10
    arguments:
      $decoratedNormalizer: '@Ivoz\Api\Operation\Factory\SubresourceOperationFactoryDecorator.inner'
      $propertyNameCollectionFactory: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyNameCollectionFactory'

  ################################################
  ## Services decorators
  ################################################
  Ivoz\Api\JsonLd\Serializer\Normalizer\EntityNormalizer:
    arguments:
      $resourceMetadataFactory: "@api_platform.metadata.resource.metadata_factory"
      $iriConverter: "@api_platform.iri_converter"
      $resourceClassResolver: "@api_platform.resource_class_resolver"
      $contextBuilder: "@api_platform.jsonld.context_builder"
    tags:
      -  { name: serializer.normalizer, priority: 10 }

  Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory:
    decorates: 'api_platform.metadata.property.metadata_factory'
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Property\Factory\PropertyMetadataLinkFactory.inner'

  Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\ResourceMetadataFactory:
    decorates: "api_platform.metadata.resource.metadata_factory"
    decoration_priority: 1
    arguments:
      $decorated: '@Ivoz\Api\Swagger\Metadata\Resource\ResourceMetadata\ResourceMetadataFactory.inner'


  ################################################
  ## UI
  ################################################
  api_platform.swagger.action.ui:
    class: Ivoz\Api\Swagger\Ui\SwaggerUiAction
    arguments:
      - "@api_platform.metadata.resource.name_collection_factory"
      - "@api_platform.metadata.resource.metadata_factory"
      - "@api_platform.serializer"
      - "@twig"
      - "@router"
      - '%api_platform.title%'
      - '%api_platform.description%'
      - '%api_platform.version%'
      - '%api_platform.formats%'
      - '%api_platform.oauth.enabled%'
      - '%api_platform.oauth.clientId%'
      - '%api_platform.oauth.clientSecret%'
      - '%api_platform.oauth.type%'
      - '%api_platform.oauth.flow%'
      - '%api_platform.oauth.tokenUrl%'
      - '%api_platform.oauth.authorizationUrl%'
      - '%api_platform.oauth.scopes%'
      - '%kernel.environment%'