imports:
  - { resource: "@CoreBundle/Resources/config/config.yml" }
  - { resource: "@CoreBundle/Resources/config/logger.yml" }
  - { resource: "@CoreBundle/Resources/config/doctrine_cache.yml" }

framework:
  secret: '%secret%'
  router:
    resource: '%kernel.root_dir%/config/routing.yml'