imports:
  - { resource: "@CoreBundle/Resources/config/config.yml" }
  - { resource: "@ApiBundle/Resources/config/config.yml" }
  - { resource: "@CoreBundle/Resources/config/logger.yml" }
  - { resource: "@CoreBundle/Resources/config/doctrine_cache.yml" }
  - { resource: "api_platform.yml" }
  - { resource: "security.yml" }
  - { resource: "services.yml" }
